// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: post.proto

package post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortType int32

const (
	SortType_SORT_TYPE_DEFAULT SortType = 0
	SortType_SORT_TYPE_HOT     SortType = 1
	SortType_SORT_TYPE_NEW     SortType = 2
)

// Enum value maps for SortType.
var (
	SortType_name = map[int32]string{
		0: "SORT_TYPE_DEFAULT",
		1: "SORT_TYPE_HOT",
		2: "SORT_TYPE_NEW",
	}
	SortType_value = map[string]int32{
		"SORT_TYPE_DEFAULT": 0,
		"SORT_TYPE_HOT":     1,
		"SORT_TYPE_NEW":     2,
	}
)

func (x SortType) Enum() *SortType {
	p := new(SortType)
	*p = x
	return p
}

func (x SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_post_proto_enumTypes[0].Descriptor()
}

func (SortType) Type() protoreflect.EnumType {
	return &file_post_proto_enumTypes[0]
}

func (x SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortType.Descriptor instead.
func (SortType) EnumDescriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

type PostListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PostType      int32                  `protobuf:"varint,10,opt,name=post_type,json=postType,proto3" json:"post_type,omitempty"`
	Sort          SortType               `protobuf:"varint,11,opt,name=sort,proto3,enum=mono.post.SortType" json:"sort,omitempty"`
	Uid           int64                  `protobuf:"varint,20,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostListReq) Reset() {
	*x = PostListReq{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostListReq) ProtoMessage() {}

func (x *PostListReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostListReq.ProtoReflect.Descriptor instead.
func (*PostListReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PostListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PostListReq) GetPostType() int32 {
	if x != nil {
		return x.PostType
	}
	return 0
}

func (x *PostListReq) GetSort() SortType {
	if x != nil {
		return x.Sort
	}
	return SortType_SORT_TYPE_DEFAULT
}

func (x *PostListReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type PostListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostListItem        `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostListResp) Reset() {
	*x = PostListResp{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostListResp) ProtoMessage() {}

func (x *PostListResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostListResp.ProtoReflect.Descriptor instead.
func (*PostListResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *PostListResp) GetPosts() []*PostListItem {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *PostListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PostListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	PostId        int64                  `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Uid           int64                  `protobuf:"varint,10,opt,name=uid,proto3" json:"uid,omitempty"`
	Avatar        string                 `protobuf:"bytes,11,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname      string                 `protobuf:"bytes,12,opt,name=nickname,proto3" json:"nickname,omitempty"`
	LikeCount     int32                  `protobuf:"varint,20,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CollectCount  int32                  `protobuf:"varint,21,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	CommentCount  int32                  `protobuf:"varint,22,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ViewCount     int32                  `protobuf:"varint,23,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,24,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	IsTopped      bool                   `protobuf:"varint,30,opt,name=is_topped,json=isTopped,proto3" json:"is_topped,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,39,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostListItem) Reset() {
	*x = PostListItem{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostListItem) ProtoMessage() {}

func (x *PostListItem) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostListItem.ProtoReflect.Descriptor instead.
func (*PostListItem) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *PostListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostListItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostListItem) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostListItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PostListItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PostListItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PostListItem) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostListItem) GetCollectCount() int32 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *PostListItem) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *PostListItem) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PostListItem) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *PostListItem) GetIsTopped() bool {
	if x != nil {
		return x.IsTopped
	}
	return false
}

func (x *PostListItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type PostCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	PostType      int32                  `protobuf:"varint,4,opt,name=post_type,json=postType,proto3" json:"post_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCreateReq) Reset() {
	*x = PostCreateReq{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCreateReq) ProtoMessage() {}

func (x *PostCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCreateReq.ProtoReflect.Descriptor instead.
func (*PostCreateReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *PostCreateReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PostCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostCreateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostCreateReq) GetPostType() int32 {
	if x != nil {
		return x.PostType
	}
	return 0
}

type PostDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetailReq) Reset() {
	*x = PostDetailReq{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetailReq) ProtoMessage() {}

func (x *PostDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetailReq.ProtoReflect.Descriptor instead.
func (*PostDetailReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *PostDetailReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostDetailReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type PostDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Uid           int64                  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	LikeCount     int32                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CollectCount  int32                  `protobuf:"varint,11,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	ViewCount     int32                  `protobuf:"varint,13,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,14,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetailResp) Reset() {
	*x = PostDetailResp{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetailResp) ProtoMessage() {}

func (x *PostDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetailResp.ProtoReflect.Descriptor instead.
func (*PostDetailResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *PostDetailResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostDetailResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostDetailResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PostDetailResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PostDetailResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PostDetailResp) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *PostDetailResp) GetCollectCount() int32 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *PostDetailResp) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *PostDetailResp) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type PostCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Uid           int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentReq) Reset() {
	*x = PostCommentReq{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentReq) ProtoMessage() {}

func (x *PostCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentReq.ProtoReflect.Descriptor instead.
func (*PostCommentReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *PostCommentReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostCommentReq) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *PostCommentReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PostCommentReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type PostCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentComment []*ParentComment       `protobuf:"bytes,1,rep,name=parent_comment,json=parentComment,proto3" json:"parent_comment,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommentResp) Reset() {
	*x = PostCommentResp{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommentResp) ProtoMessage() {}

func (x *PostCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommentResp.ProtoReflect.Descriptor instead.
func (*PostCommentResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

func (x *PostCommentResp) GetParentComment() []*ParentComment {
	if x != nil {
		return x.ParentComment
	}
	return nil
}

func (x *PostCommentResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ParentComment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommentId       int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Uid             int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ChildrenComment []*ChildrenComment     `protobuf:"bytes,4,rep,name=children_comment,json=childrenComment,proto3" json:"children_comment,omitempty"`
	ReplyCount      int64                  `protobuf:"varint,5,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsLiked         bool                   `protobuf:"varint,10,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParentComment) Reset() {
	*x = ParentComment{}
	mi := &file_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentComment) ProtoMessage() {}

func (x *ParentComment) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentComment.ProtoReflect.Descriptor instead.
func (*ParentComment) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{8}
}

func (x *ParentComment) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ParentComment) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ParentComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParentComment) GetChildrenComment() []*ChildrenComment {
	if x != nil {
		return x.ChildrenComment
	}
	return nil
}

func (x *ParentComment) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *ParentComment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ParentComment) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type ChildrenComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ReplyUid      int64                  `protobuf:"varint,3,opt,name=reply_uid,json=replyUid,proto3" json:"reply_uid,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsLiked       bool                   `protobuf:"varint,10,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildrenComment) Reset() {
	*x = ChildrenComment{}
	mi := &file_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildrenComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildrenComment) ProtoMessage() {}

func (x *ChildrenComment) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildrenComment.ProtoReflect.Descriptor instead.
func (*ChildrenComment) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{9}
}

func (x *ChildrenComment) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ChildrenComment) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChildrenComment) GetReplyUid() int64 {
	if x != nil {
		return x.ReplyUid
	}
	return 0
}

func (x *ChildrenComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChildrenComment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChildrenComment) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type SetCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      int64                  `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ReplyUid      int64                  `protobuf:"varint,5,opt,name=reply_uid,json=replyUid,proto3" json:"reply_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCommentReq) Reset() {
	*x = SetCommentReq{}
	mi := &file_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCommentReq) ProtoMessage() {}

func (x *SetCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCommentReq.ProtoReflect.Descriptor instead.
func (*SetCommentReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{10}
}

func (x *SetCommentReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *SetCommentReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SetCommentReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *SetCommentReq) GetReplyUid() int64 {
	if x != nil {
		return x.ReplyUid
	}
	return 0
}

type SetLikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType    int32                  `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Uid           int64                  `protobuf:"varint,10,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLikeReq) Reset() {
	*x = SetLikeReq{}
	mi := &file_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLikeReq) ProtoMessage() {}

func (x *SetLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLikeReq.ProtoReflect.Descriptor instead.
func (*SetLikeReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{11}
}

func (x *SetLikeReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SetLikeReq) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *SetLikeReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\tmono.post\x1a\x1bgoogle/protobuf/empty.proto\"\x96\x01\n" +
	"\vPostListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tpost_type\x18\n" +
	" \x01(\x05R\bpostType\x12'\n" +
	"\x04sort\x18\v \x01(\x0e2\x13.mono.post.SortTypeR\x04sort\x12\x10\n" +
	"\x03uid\x18\x14 \x01(\x03R\x03uid\"S\n" +
	"\fPostListResp\x12-\n" +
	"\x05posts\x18\x01 \x03(\v2\x17.mono.post.PostListItemR\x05posts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xfc\x02\n" +
	"\fPostListItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x03R\x06postId\x12\x10\n" +
	"\x03uid\x18\n" +
	" \x01(\x03R\x03uid\x12\x16\n" +
	"\x06avatar\x18\v \x01(\tR\x06avatar\x12\x1a\n" +
	"\bnickname\x18\f \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"like_count\x18\x14 \x01(\x05R\tlikeCount\x12#\n" +
	"\rcollect_count\x18\x15 \x01(\x05R\fcollectCount\x12#\n" +
	"\rcomment_count\x18\x16 \x01(\x05R\fcommentCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x17 \x01(\x05R\tviewCount\x12\x19\n" +
	"\bis_liked\x18\x18 \x01(\bR\aisLiked\x12\x1b\n" +
	"\tis_topped\x18\x1e \x01(\bR\bisTopped\x12\x1d\n" +
	"\n" +
	"created_at\x18' \x01(\x03R\tcreatedAt\"n\n" +
	"\rPostCreateReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tpost_type\x18\x04 \x01(\x05R\bpostType\":\n" +
	"\rPostDetailReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"\x84\x02\n" +
	"\x0ePostDetailResp\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x05R\tlikeCount\x12#\n" +
	"\rcollect_count\x18\v \x01(\x05R\fcollectCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\r \x01(\x05R\tviewCount\x12\x19\n" +
	"\bis_liked\x18\x0e \x01(\bR\aisLiked\"p\n" +
	"\x0ePostCommentReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\"m\n" +
	"\x0fPostCommentResp\x12?\n" +
	"\x0eparent_comment\x18\x01 \x03(\v2\x18.mono.post.ParentCommentR\rparentComment\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xfc\x01\n" +
	"\rParentComment\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12E\n" +
	"\x10children_comment\x18\x04 \x03(\v2\x1a.mono.post.ChildrenCommentR\x0fchildrenComment\x12\x1f\n" +
	"\vreply_count\x18\x05 \x01(\x03R\n" +
	"replyCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x19\n" +
	"\bis_liked\x18\n" +
	" \x01(\bR\aisLiked\"\xb3\x01\n" +
	"\x0fChildrenComment\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x1b\n" +
	"\treply_uid\x18\x03 \x01(\x03R\breplyUid\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x19\n" +
	"\bis_liked\x18\n" +
	" \x01(\bR\aisLiked\"\x8e\x01\n" +
	"\rSetCommentReq\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\x03R\bparentId\x12\x1b\n" +
	"\treply_uid\x18\x05 \x01(\x03R\breplyUid\"\\\n" +
	"\n" +
	"SetLikeReq\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x10\n" +
	"\x03uid\x18\n" +
	" \x01(\x03R\x03uid*G\n" +
	"\bSortType\x12\x15\n" +
	"\x11SORT_TYPE_DEFAULT\x10\x00\x12\x11\n" +
	"\rSORT_TYPE_HOT\x10\x01\x12\x11\n" +
	"\rSORT_TYPE_NEW\x10\x022\x84\x03\n" +
	"\x04Post\x127\n" +
	"\x04List\x12\x16.mono.post.PostListReq\x1a\x17.mono.post.PostListResp\x12:\n" +
	"\x06Create\x12\x18.mono.post.PostCreateReq\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x06Detail\x12\x18.mono.post.PostDetailReq\x1a\x19.mono.post.PostDetailResp\x12G\n" +
	"\x0eGetPostComment\x12\x19.mono.post.PostCommentReq\x1a\x1a.mono.post.PostCommentResp\x12>\n" +
	"\n" +
	"SetComment\x12\x18.mono.post.SetCommentReq\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x0eSetLikeComment\x12\x15.mono.post.SetLikeReq\x1a\x16.google.protobuf.EmptyB\x0eZ\fmono/pb/postb\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_post_proto_goTypes = []any{
	(SortType)(0),           // 0: mono.post.SortType
	(*PostListReq)(nil),     // 1: mono.post.PostListReq
	(*PostListResp)(nil),    // 2: mono.post.PostListResp
	(*PostListItem)(nil),    // 3: mono.post.PostListItem
	(*PostCreateReq)(nil),   // 4: mono.post.PostCreateReq
	(*PostDetailReq)(nil),   // 5: mono.post.PostDetailReq
	(*PostDetailResp)(nil),  // 6: mono.post.PostDetailResp
	(*PostCommentReq)(nil),  // 7: mono.post.PostCommentReq
	(*PostCommentResp)(nil), // 8: mono.post.PostCommentResp
	(*ParentComment)(nil),   // 9: mono.post.ParentComment
	(*ChildrenComment)(nil), // 10: mono.post.ChildrenComment
	(*SetCommentReq)(nil),   // 11: mono.post.SetCommentReq
	(*SetLikeReq)(nil),      // 12: mono.post.SetLikeReq
	(*emptypb.Empty)(nil),   // 13: google.protobuf.Empty
}
var file_post_proto_depIdxs = []int32{
	0,  // 0: mono.post.PostListReq.sort:type_name -> mono.post.SortType
	3,  // 1: mono.post.PostListResp.posts:type_name -> mono.post.PostListItem
	9,  // 2: mono.post.PostCommentResp.parent_comment:type_name -> mono.post.ParentComment
	10, // 3: mono.post.ParentComment.children_comment:type_name -> mono.post.ChildrenComment
	1,  // 4: mono.post.Post.List:input_type -> mono.post.PostListReq
	4,  // 5: mono.post.Post.Create:input_type -> mono.post.PostCreateReq
	5,  // 6: mono.post.Post.Detail:input_type -> mono.post.PostDetailReq
	7,  // 7: mono.post.Post.GetPostComment:input_type -> mono.post.PostCommentReq
	11, // 8: mono.post.Post.SetComment:input_type -> mono.post.SetCommentReq
	12, // 9: mono.post.Post.SetLikeComment:input_type -> mono.post.SetLikeReq
	2,  // 10: mono.post.Post.List:output_type -> mono.post.PostListResp
	13, // 11: mono.post.Post.Create:output_type -> google.protobuf.Empty
	6,  // 12: mono.post.Post.Detail:output_type -> mono.post.PostDetailResp
	8,  // 13: mono.post.Post.GetPostComment:output_type -> mono.post.PostCommentResp
	13, // 14: mono.post.Post.SetComment:output_type -> google.protobuf.Empty
	13, // 15: mono.post.Post.SetLikeComment:output_type -> google.protobuf.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		EnumInfos:         file_post_proto_enumTypes,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
