pgsql:
  host: localhost
  user: admin
  pwd: 123456
  port: 5433
service:
  auth:
    grpc: localhost
    port: 9900
  post:
    grpc: localhost
    port: 9910
  user:
    grpc: localhost
    port: 9920