// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePost = "post"

// Post mapped from table <post>
type Post struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID          int64          `gorm:"column:uid;not null;comment:所属用户id" json:"uid"`                       // 所属用户id
	Title        string         `gorm:"column:title;not null;comment:标题" json:"title"`                       // 标题
	Content      string         `gorm:"column:content;not null;comment:正文" json:"content"`                   // 正文
	PostType     int16          `gorm:"column:post_type;not null;default:1;comment:1=普通帖子" json:"post_type"` // 1=普通帖子
	LikeCount    int32          `gorm:"column:like_count;not null;comment:点赞数" json:"like_count"`            // 点赞数
	CommentCount int32          `gorm:"column:comment_count;not null;comment:评论数" json:"comment_count"`      // 评论数
	CollectCount int32          `gorm:"column:collect_count;not null;comment:收藏数" json:"collect_count"`      // 收藏数
	ViewCount    int32          `gorm:"column:view_count;not null;comment:浏览量" json:"view_count"`            // 浏览量
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
