// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type BatchGetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []int64                `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserReq) Reset() {
	*x = BatchGetUserReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserReq) ProtoMessage() {}

func (x *BatchGetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetUserReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type BatchGetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         map[int64]*GetUserResp `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserResp) Reset() {
	*x = BatchGetUserResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserResp) ProtoMessage() {}

func (x *BatchGetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserResp.ProtoReflect.Descriptor instead.
func (*BatchGetUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetUserResp) GetUsers() map[int64]*GetUserResp {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x0erpc.proto.user\"\x1e\n" +
	"\n" +
	"GetUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"S\n" +
	"\vGetUserResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"%\n" +
	"\x0fBatchGetUserReq\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\x03R\x04uids\"\xac\x01\n" +
	"\x10BatchGetUserResp\x12A\n" +
	"\x05users\x18\x01 \x03(\v2+.rpc.proto.user.BatchGetUserResp.UsersEntryR\x05users\x1aU\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.rpc.proto.user.GetUserRespR\x05value:\x028\x012\xa5\x01\n" +
	"\x04User\x12F\n" +
	"\vGetUserInfo\x12\x1a.rpc.proto.user.GetUserReq\x1a\x1b.rpc.proto.user.GetUserResp\x12U\n" +
	"\x10BatchGetUserInfo\x12\x1f.rpc.proto.user.BatchGetUserReq\x1a .rpc.proto.user.BatchGetUserRespB\tZ\amono/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_proto_goTypes = []any{
	(*GetUserReq)(nil),       // 0: rpc.proto.user.GetUserReq
	(*GetUserResp)(nil),      // 1: rpc.proto.user.GetUserResp
	(*BatchGetUserReq)(nil),  // 2: rpc.proto.user.BatchGetUserReq
	(*BatchGetUserResp)(nil), // 3: rpc.proto.user.BatchGetUserResp
	nil,                      // 4: rpc.proto.user.BatchGetUserResp.UsersEntry
}
var file_user_proto_depIdxs = []int32{
	4, // 0: rpc.proto.user.BatchGetUserResp.users:type_name -> rpc.proto.user.BatchGetUserResp.UsersEntry
	1, // 1: rpc.proto.user.BatchGetUserResp.UsersEntry.value:type_name -> rpc.proto.user.GetUserResp
	0, // 2: rpc.proto.user.User.GetUserInfo:input_type -> rpc.proto.user.GetUserReq
	2, // 3: rpc.proto.user.User.BatchGetUserInfo:input_type -> rpc.proto.user.BatchGetUserReq
	1, // 4: rpc.proto.user.User.GetUserInfo:output_type -> rpc.proto.user.GetUserResp
	3, // 5: rpc.proto.user.User.BatchGetUserInfo:output_type -> rpc.proto.user.BatchGetUserResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
